#!/bin/sh
# profile for interactive shells
case "$-" in
    *i*) ;;
    *) return ;;
esac

[ "$(echo $TERM)" = "rxvt-unicode" ] && export TERM=rxvt-unicode-256color

if [ -n "$BASH_VERSION" ]; then
    . "$XDG_CONFIG_HOME/bashrc"
fi

[ -f "$XDG_CONFIG_HOME/shell_aliases" ] && . "$XDG_CONFIG_HOME/shell_aliases"
[ -f "$XDG_CONFIG_HOME/shell_aliases.local" ] && . "$XDG_CONFIG_HOME/shell_aliases.local"

newpass () {
    length="$1"
    head /dev/urandom | tr -dc A-Za-z0-9 | head -c "$length" ; echo ''
}
