#!/bin/bash
if [ -z "$BASH_VERSION" ]; then
    return
fi

# Set a few defaults
shopt -s checkwinsize
shopt -s autocd
set -o vi

# Source bash completion
[ -f "/usr/share/bash-completion/bash_completion" ] && \
    . "/usr/share/bash-completion/bash_completion"

